sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t lucasapereira/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lucasapereira/docker-react npm run test